version: '3.8'
services:
  db:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongestPassword666
      - MSSQL_PID=Express
    network_mode: host

